# Fork of Unreal style from ImThemes
alpha = 1.0
disabledAlpha = 0.6
windowPadding = [8.0, 8.0]
windowRounding = 0.0
windowBorderSize = 1.0
windowMinSize = [32.0, 32.0]
windowTitleAlign = [0.0, 0.5]
windowMenuButtonPosition = "Left"
childRounding = 0.0
childBorderSize = 1.0
popupRounding = 0.0
popupBorderSize = 1.0
framePadding = [4.0, 3.0]
frameRounding = 3.5
frameBorderSize = 0.0
itemSpacing = [8.0, 4.0]
itemInnerSpacing = [4.0, 4.0]
cellPadding = [4.0, 2.0]
indentSpacing = 21.0
columnsMinSpacing = 6.0
scrollbarSize = 14.0
scrollbarRounding = 9.0
grabMinSize = 10.0
grabRounding = 2.3
tabRounding = 4.0
tabBorderSize = 0.0
tabMinWidthForCloseButton = 0.0
colorButtonPosition = "Right"
buttonTextAlign = [0.5, 0.5]
selectableTextAlign = [0.0, 0.0]

[colors]
Text = "rgba(255, 255, 255, 1.0)"
TextDisabled = "rgba(127, 127, 127, 1.0)"
WindowBg = "rgba(19, 19, 19, 0.94)"
ChildBg = "rgba(255, 255, 255, 0.0)"
PopupBg = "rgba(20, 20, 20, 0.94)"
Border = "rgba(109, 109, 127, 0.5)"
BorderShadow = "rgba(0, 0, 0, 0.0)"
FrameBg = "rgba(51, 53, 56, 0.54)"
FrameBgHovered = "rgba(102, 102, 102, 0.4)"
FrameBgActive = "rgba(45, 45, 45, 0.67)"
TitleBg = "rgba(52, 80, 115, 1.0)"
TitleBgActive = "rgba(73, 73, 73, 1.0)"
TitleBgCollapsed = "rgba(0, 0, 0, 0.51)"
MenuBarBg = "rgba(35, 35, 35, 1.0)"
ScrollbarBg = "rgba(5, 5, 5, 0.53)"
ScrollbarGrab = "rgba(79, 79, 79, 1.0)"
ScrollbarGrabHovered = "rgba(104, 104, 104, 1.0)"
ScrollbarGrabActive = "rgba(130, 130, 130, 1.0)"
CheckMark = "rgba(239, 239, 239, 1.0)"
SliderGrab = "rgba(130, 130, 130, 1.0)"
SliderGrabActive = "rgba(219, 219, 219, 1.0)"
Button = "rgba(112, 112, 112, 0.4)"
ButtonHovered = "rgba(117, 119, 122, 1.0)"
ButtonActive = "rgba(107, 107, 107, 1.0)"
Header = "rgba(178, 178, 178, 0.31)"
HeaderHovered = "rgba(178, 178, 178, 0.8)"
HeaderActive = "rgba(122, 127, 132, 1.0)"
Separator = "rgba(109, 109, 127, 0.5)"
SeparatorHovered = "rgba(183, 183, 183, 0.78)"
SeparatorActive = "rgba(130, 130, 130, 1.0)"
ResizeGrip = "rgba(232, 232, 232, 0.25)"
ResizeGripHovered = "rgba(206, 206, 206, 0.67)"
ResizeGripActive = "rgba(117, 117, 117, 0.95)"
Tab = "rgba(45, 89, 147, 0.862)"
TabHovered = "rgba(66, 150, 249, 0.8)"
TabActive = "rgba(50, 104, 173, 1.0)"
TabUnfocused = "rgba(17, 26, 37, 0.9724)"
TabUnfocusedActive = "rgba(34, 66, 108, 1.0)"
PlotLines = "rgba(155, 155, 155, 1.0)"
PlotLinesHovered = "rgba(255, 109, 89, 1.0)"
PlotHistogram = "rgba(186, 153, 38, 1.0)"
PlotHistogramHovered = "rgba(255, 153, 0, 1.0)"
TableHeaderBg = "rgba(48, 48, 51, 1.0)"
TableBorderStrong = "rgba(79, 79, 89, 1.0)"
TableBorderLight = "rgba(58, 58, 63, 1.0)"
TableRowBg = "rgba(0, 0, 0, 0.0)"
TableRowBgAlt = "rgba(255, 255, 255, 0.06)"
TextSelectedBg = "rgba(221, 221, 221, 0.35)"
DragDropTarget = "rgba(255, 255, 0, 0.9)"
NavHighlight = "rgba(153, 153, 153, 1.0)"
NavWindowingHighlight = "rgba(255, 255, 255, 0.7)"
NavWindowingDimBg = "rgba(204, 204, 204, 0.2)"
ModalWindowDimBg = "rgba(204, 204, 204, 0.35)"