autoload_last_project = true
last_project_path = "D:\\PROJECTS\\ImperiumEngine\\ImperiumEngine\\MyProjects\\DungeonsOfLiova\\DungeonsOfLiova.ImpGame"
left_panel_width = 380
projects = [
    "D:\\PROJECTS\\ImperiumEngine\\ImperiumEngine\\MyProjects\\DungeonsOfLiova\\DungeonsOfLiova.ImpGame",
]
